name: patient-priority
channels:
  - defaults
dependencies:
  - python=3.9.7
  - pip=21.2.4
  - numpy=1.20.3
  - pandas=1.3.4
  - scikit-learn=0.24.2
  - matplotlib=3.4.3
  - seaborn=0.11.2
  - numba=0.54.1
  - pip:
      - certifi==2021.10.8
      - cloudpickle==2.0.0
      - dice-ml==0.11
      - idna==3.3
      - llvmlite==0.37.0
      - pillow==8.4.0
      - pytz==2021.3
      - raiutils==0.4.2
      - shap==0.40.0
      - six==1.16.0
      - slicer==0.0.7
      - urllib3==1.26.7
