name: patient-priority
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - ld_impl_linux-64=2.40
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=24.2
  - python=3.10.0
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - certifi==2024.12.14
      - cloudpickle==3.1.0
      - dice-ml==0.11
      - idna==3.10
      - llvmlite==0.43.0
      - numba==0.60.0
      - pillow==11.1.0
      - pytz==2024.2
      - raiutils==0.4.2
      - shap==0.46.0
      - six==1.17.0
      - slicer==0.0.8
      - urllib3==2.3.0
